// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice = never;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.sub_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Publish Date field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField;

  /**
   * Featured Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Excerpt field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField;

  /**
   * Two Columns field in *Article*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article.two_columns
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  two_columns: prismic.BooleanField;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

/**
 * Item in *BlogPage → Articles*
 */
export interface BlogpageDocumentDataArticlesItem {}

/**
 * Content for BlogPage documents
 */
interface BlogpageDocumentData {
  /**
   * Title field in *BlogPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Articles field in *BlogPage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpage.articles[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  articles: prismic.GroupField<Simplify<BlogpageDocumentDataArticlesItem>>;
}

/**
 * BlogPage document from Prismic
 *
 * - **API ID**: `blogpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogpageDocumentData>,
    "blogpage",
    Lang
  >;

/**
 * Item in *homePage → Portfolio*
 */
export interface HomepageDocumentDataPortfolioItem {
  /**
   * Title field in *homePage → Portfolio*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.portfolio[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *homePage → Portfolio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.portfolio[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * GitHub Link field in *homePage → Portfolio*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.portfolio[].githublink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  githublink: prismic.LinkField;

  /**
   * Live Link field in *homePage → Portfolio*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.portfolio[].live_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  live_link: prismic.LinkField;

  /**
   * Screenshot field in *homePage → Portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.portfolio[].screenshot
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screenshot: prismic.ImageField<never>;

  /**
   * next field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].next
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  next: prismic.BooleanField;

  /**
   * typeScript field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].typescript
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  typescript: prismic.BooleanField;

  /**
   * tailwind field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].tailwind
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  tailwind: prismic.BooleanField;

  /**
   * prismic field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].prismic
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  prismic: prismic.BooleanField;

  /**
   * formspree field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].formspree
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  formspree: prismic.BooleanField;

  /**
   * vercel field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].vercel
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  vercel: prismic.BooleanField;

  /**
   * react field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].react
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  react: prismic.BooleanField;

  /**
   * wordpress field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].wordpress
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  wordpress: prismic.BooleanField;

  /**
   * php field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].php
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  php: prismic.BooleanField;

  /**
   * sass field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].sass
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  sass: prismic.BooleanField;

  /**
   * javaScript field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].javascript
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  javascript: prismic.BooleanField;

  /**
   * css field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].css
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  css: prismic.BooleanField;

  /**
   * flow field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].flow
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  flow: prismic.BooleanField;

  /**
   * html field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].html
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  html: prismic.BooleanField;

  /**
   * mui field in *homePage → Portfolio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.portfolio[].mui
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  mui: prismic.BooleanField;
}

/**
 * Item in *homePage → Testimonials*
 */
export interface HomepageDocumentDataTestimonialsItem {
  /**
   * Quote field in *homePage → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Name field in *homePage → Testimonials*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Affiliation field in *homePage → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].affiliation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  affiliation: prismic.RichTextField;

  /**
   * Profile Picture field in *homePage → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].profile_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_picture: prismic.ImageField<never>;
}

/**
 * Item in *homePage → Clients*
 */
export interface HomepageDocumentDataClientsItem {
  /**
   * Client Logo field in *homePage → Clients*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.clients[].client_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  client_logo: prismic.ImageField<never>;
}

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for homePage documents
 */
interface HomepageDocumentData {
  /**
   * Heading field in *homePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * About Me Heading field in *homePage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.about_me_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_me_heading: prismic.TitleField;

  /**
   * Profile Picture field in *homePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.profile_picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_picture: prismic.ImageField<never>;

  /**
   * About Me Body field in *homePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.about_me_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_me_body: prismic.RichTextField;

  /**
   * Portfolio Heading field in *homePage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.portfolio_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  portfolio_heading: prismic.TitleField;

  /**
   * Portfolio field in *homePage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.portfolio[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  portfolio: prismic.GroupField<Simplify<HomepageDocumentDataPortfolioItem>>;

  /**
   * Testimonial Heading field in *homePage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonial_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonial_heading: prismic.TitleField;

  /**
   * Testimonials field in *homePage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<HomepageDocumentDataTestimonialsItem>
  >;

  /**
   * Clients field in *homePage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.clients[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  clients: prismic.GroupField<Simplify<HomepageDocumentDataClientsItem>>;

  /**
   * Slice Zone field in *homePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * homePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | BlogpageDocument
  | HomepageDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      BlogpageDocument,
      BlogpageDocumentData,
      BlogpageDocumentDataArticlesItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataPortfolioItem,
      HomepageDocumentDataTestimonialsItem,
      HomepageDocumentDataClientsItem,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
